name: Deploy html site to gh pages

on:
  push:
    branches: ["main"]
  schedule:
    # Schedule weekly builds on master, to ensure that the Docker image gets
    # rebuilt regularly (in order to include security fixes in the base image).
    - cron: '5 4 * * 5'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    name: publish docker image
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: "${{ secrets.DOCKER_USERNAME }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
    steps:
      - uses: actions/checkout@v7
      - name: Fetch repository tags (for git describe to work)
        run: git fetch --prune --unshallow
      - name: Export env vars
        run: |
          set -euxo pipefail
          export RELEASE=$(git describe --tags)
          if [ -z "$RELEASE" ]; then echo "Could not determine release name"; exit 1; fi
          echo "export DOCKER_TAGS='openhsr/gamejam:latest openhsr/gamejam:${RELEASE}'" >> .ci-env
      - name: Build Docker image
        run: | 
          set -euxo pipefail
          source .ci-env
          docker build --file=./Dockerfile --tag=openhsr/gamejam .
          for tag in $DOCKER_TAGS; do
              docker tag openhsr/gamejam "$tag"
          done
      - name: Publish Docker image
        run: |
          set -euxo pipefail
          source .ci-env 
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          for tag in $DOCKER_TAGS; do
              docker push "$tag"
          done
